import { query } from "../config/database.js";

// Create Sale
export async function addScrapSale(saleData, items) {
    const saleSql = `
        INSERT INTO scrap_sales 
        (type, project, building_site, client, scrap_date, note, sub_total, discount, total, received_amount, payment_type, bank_account, cheque_date, cheque_no, issuing_bank_name, issuing_branch_name)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    `;

    const saleValues = [
        saleData.type,
        saleData.project,
        saleData.building_site,
        saleData.client,
        saleData.scrap_date,
        saleData.note,
        saleData.sub_total,
        saleData.discount,
        saleData.total,
        saleData.received_amount,
        saleData.payment_type,
        saleData.bank_account || null,
        saleData.cheque_date || null,
        saleData.cheque_no || null,
        saleData.issuing_bank_name || null,
        saleData.issuing_branch_name || null
    ];

    // Insert sale
    await query(saleSql, saleValues);

    //Get the UUID generated by MySQL for the last inserted row
    const [result] = await query("SELECT id FROM scrap_sales ORDER BY created_at DESC LIMIT 1");
    const scrapSaleId = result.id;

    // Insert sale items
    for (const item of items) {
        const itemSql = `
            INSERT INTO scrap_sale_items 
            (scrap_sale_id, project, building_site, product, unit, stock, unit_price, quantity, total)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        `;

        const itemValues = [
            scrapSaleId,
            item.project,
            item.building_site,
            item.product,
            item.unit,
            item.stock,
            item.unit_price,
            item.quantity,
            item.total
        ];

        await query(itemSql, itemValues);
    }

    return scrapSaleId;
}



// Read All
export async function getAllScrapSales() {
    const sales = await query("SELECT * FROM scrap_sales ORDER BY created_at DESC");
    return sales;
}


// Read One
export async function getScrapSaleById(id) {
    const saleResult = await query("SELECT * FROM scrap_sales WHERE id = ?", [id]);

    if (saleResult.length === 0) return null;

    const sale = saleResult[0];

    const items = await query(`
        SELECT id, project, building_site, product, unit, stock, unit_price, quantity, total 
        FROM scrap_sale_items 
        WHERE scrap_sale_id = ?
    `, [id]);
    sale.items = items;

    return sale;
}


// Update
export async function updateScrapSale(id, data, items) {
    const updateSql = `
        UPDATE scrap_sales SET
        type = ?, project = ?, building_site = ?, client = ?, scrap_date = ?, note = ?, 
        sub_total = ?, discount = ?, total = ?, received_amount = ?, payment_type = ?,
        bank_account = ?, cheque_date = ?, cheque_no = ?, issuing_bank_name = ?, issuing_branch_name = ?
        WHERE id = ?
    `;
    const updateValues = [
        data.type,
        data.project,
        data.building_site,
        data.client,
        data.scrap_date,
        data.note,
        data.sub_total,
        data.discount,
        data.total,
        data.received_amount,
        data.payment_type,
        data.bank_account || null,
        data.cheque_date || null,
        data.cheque_no || null,
        data.issuing_bank_name || null,
        data.issuing_branch_name || null,
        id
    ];

    await query(updateSql, updateValues);
    await query("DELETE FROM scrap_sale_items WHERE scrap_sale_id = ?", [id]);

    for (const item of items) {
        await query(`
            INSERT INTO scrap_sale_items 
            (scrap_sale_id, project, building_site, product, unit, stock, unit_price, quantity, total)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        `, [
            id,
            item.project,
            item.building_site,
            item.product,
            item.unit,
            item.stock,
            item.unit_price,
            item.quantity,
            item.total
        ]);
    }
}

// Delete
export async function deleteScrapSale(id) {
    await query("DELETE FROM scrap_sales WHERE id = ?", [id]);
}
